### PR TITLE
Allow reference validators to specify if a project is a valid target

### LINKED ISSUE #44: Global java element search slow when liferay-portal source is open
Steps to reproduce

1. install eclipse-wtp-xml-search
2. install extension to xml-search like liferay-ide which contains many <toJava> references 
3. open liferay portal project from source
4. open some right like UserLocalService and then select the class and do a global project search "References > Workspace" 

This process takes a very long time in my test environment, over 1 minute.  And most of the time at least 50 seconds looks like the XMLReferencesJavaSearchParticpant is active.  I'm attaching a threaddump that shows the two active threads are related to xml search.  https://gist.github.com/gamerson/487e2b01e75c6b4082cc

### PR DESCRIPTION
**Pull request by gamerson**
fixes #44

### CODE REVIEW

**Comment by angelozerr** [comment]
Thanks @gamerson !

Could you please add some use of this interface please. Thanks!

**Comment by gamerson** [comment]
Sure thing I can add a link to our extension for this when we push it to
LiferayIDE.

Could you give the CI server a kick so we can integrate the new build?
 thanks.

On Wed, Jan 28, 2015 at 9:43 PM, Angelo <notifications@github.com> wrote:

> Thanks @gamerson <https://github.com/gamerson> !
>
> Could you please add some use of this interface please. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angelozerr/eclipse-wtp-xml-search/pull/45#issuecomment-71836247>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by angelozerr** [comment]
Build seems to be finished.

**Comment by gamerson** [comment]
Didn't get published to here yet:
http://oss.opensagres.fr/eclipse-wtp-xml-search/1.0.0-SNAPSHOT/

On Wed, Jan 28, 2015 at 10:42 PM, Angelo <notifications@github.com> wrote:

> Build seems to be finished.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angelozerr/eclipse-wtp-xml-search/pull/45#issuecomment-71844952>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by gamerson** [comment]
Sorry looking in the wrong spot :P
http://oss.opensagres.fr/eclipse-wtp-xml-search/1.0.1-SNAPSHOT/

On Thu, Jan 29, 2015 at 10:09 AM, Greg Amerson <gregory.amerson@liferay.com>
wrote:

> Didn't get published to here yet:
> http://oss.opensagres.fr/eclipse-wtp-xml-search/1.0.0-SNAPSHOT/
>
> On Wed, Jan 28, 2015 at 10:42 PM, Angelo <notifications@github.com> wrote:
>
>> Build seems to be finished.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/angelozerr/eclipse-wtp-xml-search/pull/45#issuecomment-71844952>
>> .
>>
>
>
>
> --
> Greg Amerson
> Liferay Developer Tools
> Liferay, Inc. www.liferay.com
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by gamerson** [comment]
@angelozerr Here is an example of how we extend this new interface:

https://github.com/liferay/liferay-ide/commit/eada04f0ffee0d7f5ea3de014ef16a2bb0a8d373

Particularly here:
https://github.com/liferay/liferay-ide/blob/eada04f0ffee0d7f5ea3de014ef16a2bb0a8d373/tools/plugins/com.liferay.ide.xml.search.ui/src/com/liferay/ide/xml/search/ui/validators/LiferayBaseValidator.java#L427-441

**Pull request merged**
